const WHATSAPP = '212656903345';
const defaultProducts = [
  {id:'p1',name:'منظم الطاولة الخشبي',price:149,category:'تنظيم المنزل',description:'ترتيب أنيق للمكتب أو الطاولة، بلمسة دافئة وعملية.',image:'https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=900&q=85',featured:true},
  {id:'p2',name:'قنينة الماء الحرارية',price:119,category:'أساسيات يومية',description:'كتحافظ على السخونية والبرودة، مناسبة للخدمة والخرجات.',image:'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=900&q=85',featured:true},
  {id:'p3',name:'حقيبة عملية يومية',price:189,category:'إكسسوارات',description:'خفيفة، مريحة، وفيها المساحة اللي تحتاج فالنهار ديالك.',image:'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=85',featured:true}
];
let products = JSON.parse(localStorage.getItem('dima12-products') || 'null') || defaultProducts;
let orders = JSON.parse(localStorage.getItem('dima12-orders') || '[]');
let cart = JSON.parse(localStorage.getItem('dima12-cart') || '[]');
const $ = s => document.querySelector(s);
const money = v => `${Number(v).toLocaleString('fr-MA')} درهم`;
function persist(){localStorage.setItem('dima12-products',JSON.stringify(products));localStorage.setItem('dima12-orders',JSON.stringify(orders));localStorage.setItem('dima12-cart',JSON.stringify(cart))}
function renderProducts(){const grid=$('#productsGrid');grid.innerHTML=products.filter(p=>p.featured!==false).map(p=>`<article class="product-card"><div class="product-image"><img src="${p.image || 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=900&q=85'}" alt="${p.name}"><span class="product-label">${p.category}</span><button class="button primary quick-add" data-add="${p.id}">زيد للسلة +</button></div><div class="product-info"><div><h3>${p.name}</h3><p>${p.description}</p></div><b>${money(p.price)}</b></div></article>`).join('') || '<p>غادي نزيدو منتجات جديدة قريباً.</p>';document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addCart(b.dataset.add))}
function renderCart(){const box=$('#cartItems'),empty=$('#cartEmpty'),footer=$('#cartFooter');const expanded=cart.map(i=>({...i,p:products.find(p=>p.id===i.id)})).filter(x=>x.p);$('#cartCount').textContent=expanded.reduce((a,x)=>a+x.qty,0);box.innerHTML=expanded.map(({p,qty})=>`<div class="cart-item"><img src="${p.image}" alt=""><div><h3>${p.name}</h3><b>${money(p.price)}</b><div class="qty"><button data-qty="${p.id}" data-delta="-1">−</button><span>${qty}</span><button data-qty="${p.id}" data-delta="1">+</button></div></div><button class="remove" data-remove="${p.id}">×</button></div>`).join('');const has=expanded.length>0;empty.hidden=has;footer.hidden=!has;$('#cartTotal').textContent=money(expanded.reduce((a,x)=>a+x.p.price*x.qty,0));document.querySelectorAll('[data-qty]').forEach(b=>b.onclick=()=>updateQty(b.dataset.qty,Number(b.dataset.delta)));document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x.id!==b.dataset.remove);persist();renderCart()})}
function addCart(id){const item=cart.find(x=>x.id===id);if(item)item.qty++;else cart.push({id,qty:1});persist();renderCart();openCart()}
function updateQty(id,delta){const item=cart.find(x=>x.id===id);item.qty+=delta;if(item.qty<1)cart=cart.filter(x=>x.id!==id);persist();renderCart()}
function openCart(){$('#cartPanel').classList.add('open');$('#overlay').classList.add('open');$('#cartPanel').setAttribute('aria-hidden','false')}
function closeCart(){$('#cartPanel').classList.remove('open');$('#overlay').classList.remove('open');$('#cartPanel').setAttribute('aria-hidden','true')}
function renderDashboard(){const revenue=orders.reduce((s,o)=>s+o.total,0),customers=new Set(orders.map(o=>o.customer.phone));$('#salesTotal').innerHTML=`${revenue.toLocaleString('fr-MA')} <small>DH</small>`;$('#ordersTotal').textContent=orders.length;$('#customersTotal').textContent=customers.size;$('#averageTotal').innerHTML=`${orders.length?Math.round(revenue/orders.length).toLocaleString('fr-MA'):0} <small>DH</small>`;$('#productsNumber').textContent=`${products.length} منتوج`;$('#ordersTable').innerHTML=orders.length?orders.slice(0,8).map(o=>`<tr><td><b>${o.customer.name}</b><br><small>${o.customer.phone}</small></td><td>${o.items.map(i=>`${i.name} ×${i.qty}`).join('<br>')}</td><td>${money(o.total)}</td><td>${o.date}</td><td><span class="status ${o.status==='جديد'?'new':''}">${o.status}</span></td></tr>`).join(''):'<tr><td colspan="5" class="empty-orders">مازال ما كاين حتى طلب. ملي كيطلب الزبون، غادي يبان هنا.</td></tr>';$('#adminProducts').innerHTML=products.map(p=>`<article class="admin-product"><img src="${p.image}" alt=""><div><h3>${p.name}</h3><p>${money(p.price)} · ${p.category}</p></div><button data-edit="${p.id}">تعديل</button><button data-delete="${p.id}">حذف</button></article>`).join('');document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openProductForm(products.find(p=>p.id===b.dataset.edit)));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('واش بغيتي تحذف هاد المنتوج؟')){products=products.filter(p=>p.id!==b.dataset.delete);persist();renderProducts();renderCart();renderDashboard()}})}
function openProductForm(product){const form=$('#productForm');form.reset();$('#productModalTitle').textContent=product?'تعديل المنتوج':'زيد منتوج جديد';if(product)Object.entries(product).forEach(([k,v])=>{if(k==='featured')form.elements[k].checked=v;else if(form.elements[k])form.elements[k].value=v});$('#productModal').showModal()}
function showDashboard(){document.querySelector('body').scrollTop=0;$('#home').hidden=true;$('.site-header').hidden=true;$('.announcement').hidden=true;$('footer').hidden=true;$('.whatsapp').hidden=true;$('#dashboard').hidden=false;renderDashboard()}
function hideDashboard(){$('#dashboard').hidden=true;$('#home').hidden=false;$('.site-header').hidden=false;$('.announcement').hidden=false;$('footer').hidden=false;$('.whatsapp').hidden=false;history.replaceState(null,'','#home')}
$('#cartButton').onclick=openCart;$('#overlay').onclick=closeCart;document.querySelectorAll('[data-close="cartPanel"]').forEach(b=>b.onclick=closeCart);document.querySelectorAll('[data-close="checkoutModal"]').forEach(b=>b.onclick=()=>$('#checkoutModal').close());$('#checkoutButton').onclick=()=>{$('#checkoutModal').showModal()};$('#newProduct').onclick=()=>openProductForm();$('#leaveDashboard').onclick=hideDashboard;
$('#checkoutForm').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));const items=cart.map(x=>{const p=products.find(p=>p.id===x.id);return {...p,qty:x.qty}}).filter(Boolean);const total=items.reduce((s,x)=>s+x.price*x.qty,0);const order={id:Date.now(),customer:data,items,total,status:'جديد',date:new Date().toLocaleDateString('fr-MA')};orders.unshift(order);cart=[];persist();renderCart();renderDashboard();$('#checkoutModal').close();closeCart();const details=items.map(x=>`- ${x.name} × ${x.qty} = ${x.price*x.qty} DH`).join('\n');const message=`*طلب جديد من Dima12*\n\n${details}\n\n*المجموع: ${total} DH*\n\nالاسم: ${data.name}\nالهاتف: ${data.phone}\nالمدينة: ${data.city}\nالعنوان: ${data.address}\n\nالدفع: عند الاستلام`;window.open(`https://wa.me/${WHATSAPP}?text=${encodeURIComponent(message)}`,'_blank')};
$('#productForm').onsubmit=e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const product={...f,id:f.id||`p${Date.now()}`,price:Number(f.price),featured:$('#productForm').featured.checked,image:f.image||'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=900&q=85'};const i=products.findIndex(p=>p.id===product.id);if(i>=0)products[i]=product;else products.unshift(product);persist();renderProducts();renderDashboard();$('#productModal').close()};
$('#addDemoOrder').onclick=()=>{if(!products.length)return;const p=products[0];orders.unshift({id:Date.now(),customer:{name:'زبون تجريبي',phone:'06 00 00 00 00',city:'Casablanca',address:'اختبار'},items:[{...p,qty:1}],total:p.price,status:'تم التأكيد',date:new Date().toLocaleDateString('fr-MA')});persist();renderDashboard()};
window.addEventListener('hashchange',()=>location.hash==='#dashboard'?showDashboard():hideDashboard());$('#year').textContent=new Date().getFullYear();renderProducts();renderCart();if(location.hash==='#dashboard')showDashboard();
