/* Dima12 production store: Supabase products, image uploads and COD orders. */
const cfg = window.DIMA12_SUPABASE;
const db = window.supabase.createClient(cfg.url, cfg.publishableKey);
const $ = s => document.querySelector(s);
let products = [], cart = JSON.parse(localStorage.getItem('dima12-cart') || '[]'), activeAdmin = false;
const money = n => `${Number(n).toLocaleString('fr-MA')} درهم`;
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function saveCart(){localStorage.setItem('dima12-cart', JSON.stringify(cart))}
async function loadProducts(){const {data,error}=await db.from('products').select('*').eq('active',true).order('created_at',{ascending:false});if(error){console.error(error);return}products=data||[];renderProducts();renderCart()}
function renderProducts(){const grid=$('#productsGrid');if(!products.length){grid.innerHTML='<p style="grid-column:1/-1;color:#657879">المنتجات غادي يبانوا هنا. من لوحة الإدارة زيد أول منتوج ديالك.</p>';return}grid.innerHTML=products.filter(p=>p.featured).map(p=>{const colors=Array.isArray(p.colors)?p.colors:[];return `<article class="product-card"><div class="product-image"><img src="${esc(p.image_url||'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=900&q=85')}" alt="${esc(p.name)}"><span class="product-label">${esc(p.category)}</span><button class="button primary quick-add" data-add="${p.id}">زيد للسلة +</button></div><div class="product-info"><div><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p>${colors.length?`<select class="color-select" data-color="${p.id}"><option value="">اختار اللون</option>${colors.map(c=>`<option>${esc(c)}</option>`).join('')}</select>`:''}</div><b>${money(p.price)}</b></div></article>`}).join('');document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addCart(b.dataset.add))}
function addCart(id){const color=$(`[data-color="${id}"]`)?.value||'';const product=products.find(p=>p.id===id);if(product?.colors?.length&&!color){alert('اختار اللون أولاً');return}const item=cart.find(x=>x.id===id&&x.color===color);if(item)item.qty++;else cart.push({id,qty:1,color});saveCart();renderCart();openCart()}
function renderCart(){const full=cart.map(x=>({...x,p:products.find(p=>p.id===x.id)})).filter(x=>x.p);$('#cartCount').textContent=full.reduce((s,x)=>s+x.qty,0);$('#cartItems').innerHTML=full.map(x=>`<div class="cart-item"><img src="${esc(x.p.image_url||'')}" alt=""><div><h3>${esc(x.p.name)}${x.color?` · ${esc(x.color)}`:''}</h3><b>${money(x.p.price)}</b><div class="qty"><button data-q="${x.p.id}|${esc(x.color)}" data-d="-1">−</button><span>${x.qty}</span><button data-q="${x.p.id}|${esc(x.color)}" data-d="1">+</button></div></div><button class="remove" data-r="${x.p.id}|${esc(x.color)}">×</button></div>`).join('');const has=!!full.length;$('#cartEmpty').hidden=has;$('#cartFooter').hidden=!has;$('#cartTotal').textContent=money(full.reduce((s,x)=>s+x.p.price*x.qty,0));document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>qty(...b.dataset.q.split('|'),Number(b.dataset.d)));document.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>{const [id,color]=b.dataset.r.split('|');cart=cart.filter(x=>x.id!==id||x.color!==color);saveCart();renderCart()})}
function qty(id,color,d){const i=cart.find(x=>x.id===id&&x.color===color);i.qty+=d;if(i.qty<1)cart=cart.filter(x=>x!==i);saveCart();renderCart()}
function openCart(){$('#cartPanel').classList.add('open');$('#overlay').classList.add('open')};function closeCart(){$('#cartPanel').classList.remove('open');$('#overlay').classList.remove('open')}
async function createOrder(e){e.preventDefault();const customer=Object.fromEntries(new FormData(e.target));const lines=cart.map(x=>({...x,p:products.find(p=>p.id===x.id)})).filter(x=>x.p);if(!lines.length)return;const total=lines.reduce((s,x)=>s+x.p.price*x.qty,0);const {data:order,error}=await db.from('orders').insert({customer_name:customer.name,customer_phone:customer.phone,customer_city:customer.city,customer_address:customer.address,total}).select().single();if(error){alert('وقع مشكل، عاود حاول.');console.error(error);return}const {error:itemsError}=await db.from('order_items').insert(lines.map(x=>({order_id:order.id,product_id:x.p.id,product_name:x.p.name,unit_price:x.p.price,quantity:x.qty,selected_color:x.color||null})));if(itemsError)console.error(itemsError);const details=lines.map(x=>`- ${x.p.name}${x.color?` (${x.color})`:''} × ${x.qty} = ${x.p.price*x.qty} DH`).join('\n');cart=[];saveCart();renderCart();e.target.reset();$('#checkoutModal').close();closeCart();window.open(`https://wa.me/212656903345?text=${encodeURIComponent(`*طلب جديد Dima12 #${order.id.slice(0,8)}*\n\n${details}\n\n*المجموع: ${total} DH*\nالاسم: ${customer.name}\nالهاتف: ${customer.phone}\nالمدينة: ${customer.city}\nالعنوان: ${customer.address}\nالدفع عند الاستلام`)}`,'_blank')}
async function enterDashboard(){const {data:{session}}=await db.auth.getSession();if(!session){const email=prompt('دخل الإيميل ديال الإدارة:');if(!email)return;const password=prompt('دخل كلمة السر:');if(!password)return;const {error}=await db.auth.signInWithPassword({email,password});if(error){alert('الإيميل أو كلمة السر غير صحيحة.');return}}const {data:role,error}=await db.from('admin_users').select('user_id').limit(1);if(error||!role?.length){alert('الحساب دخل، ولكن خاصو صلاحية الإدارة. نفذ السطر الأخير في supabase-schema.sql مرة وحدة بالإيميل ديالك.');return}activeAdmin=true;$('.announcement').hidden=true;$('.site-header').hidden=true;$('#home').hidden=true;$('footer').hidden=true;$('.whatsapp').hidden=true;$('#dashboard').hidden=false;await renderDashboard()}
async function renderDashboard(){const [{data:orders,error:oErr},{data:adminProducts,error:pErr}]=await Promise.all([db.from('orders').select('*,order_items(*)').order('created_at',{ascending:false}),db.from('products').select('*').order('created_at',{ascending:false})]);if(oErr||pErr){console.error(oErr||pErr);return}const revenue=(orders||[]).reduce((s,o)=>s+Number(o.total),0);$('#salesTotal').innerHTML=`${revenue.toLocaleString('fr-MA')} <small>DH</small>`;$('#ordersTotal').textContent=orders.length;$('#customersTotal').textContent=new Set(orders.map(o=>o.customer_phone)).size;$('#averageTotal').innerHTML=`${orders.length?Math.round(revenue/orders.length).toLocaleString('fr-MA'):0} <small>DH</small>`;$('#productsNumber').textContent=`${adminProducts.length} منتوج`;$('#ordersTable').innerHTML=orders.length?orders.map(o=>`<tr><td><b>${esc(o.customer_name)}</b><br><small>${esc(o.customer_phone)}</small></td><td>${o.order_items.map(i=>`${esc(i.product_name)} ×${i.quantity}${i.selected_color?` (${esc(i.selected_color)})`:''}`).join('<br>')}</td><td>${money(o.total)}</td><td>${new Date(o.created_at).toLocaleDateString('fr-MA')}</td><td><span class="status new">${esc(o.status)}</span></td></tr>`).join(''):'<tr><td colspan="5" class="empty-orders">مازال ماكاين حتى طلب.</td></tr>';$('#adminProducts').innerHTML=adminProducts.map(p=>`<article class="admin-product"><img src="${esc(p.image_url||'')}" alt=""><div><h3>${esc(p.name)}</h3><p>${money(p.price)} · ${(p.colors||[]).map(esc).join('، ')||'بلا ألوان'}</p></div><button data-edit="${p.id}">تعديل</button><button data-del="${p.id}">حذف</button></article>`).join('');document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openProduct(adminProducts.find(p=>p.id===b.dataset.edit)));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>removeProduct(b.dataset.del))}
function openProduct(p){const f=$('#productForm');f.reset();if(p){$('#productModalTitle').textContent='تعديل المنتوج';f.id.value=p.id;f.name.value=p.name;f.price.value=p.price;f.category.value=p.category;f.description.value=p.description;f.colors.value=(p.colors||[]).join('، ');f.featured.checked=p.featured;f.existing_image.value=p.image_url||''}else $('#productModalTitle').textContent='زيد منتوج جديد';$('#productModal').showModal()}
async function saveProduct(e){e.preventDefault();const f=e.currentTarget,form=new FormData(f),file=form.get('image_file');let imageUrl=f.existing_image.value||null;if(file?.size){const ext=file.name.split('.').pop();const path=`${crypto.randomUUID()}.${ext}`;const {error}=await db.storage.from('product-images').upload(path,file,{upsert:false});if(error){alert('ماقدراتش الصورة تترفع.');console.error(error);return}imageUrl=db.storage.from('product-images').getPublicUrl(path).data.publicUrl}const product={name:form.get('name'),price:Number(form.get('price')),category:form.get('category'),description:form.get('description'),image_url:imageUrl,colors:String(form.get('colors')||'').split(/[،,]/).map(x=>x.trim()).filter(Boolean),featured:f.featured.checked,active:true};let result=f.id.value?await db.from('products').update(product).eq('id',f.id.value):await db.from('products').insert(product);if(result.error){alert('ما تحفظش المنتوج. تأكد بلي نفذتي إعدادات Supabase وصلاحية الإدارة.');console.error(result.error);return}f.reset();$('#productModal').close();await loadProducts();await renderDashboard()}
async function removeProduct(id){if(!confirm('واش بغيتي تحذف هاد المنتوج؟'))return;const {error}=await db.from('products').update({active:false}).eq('id',id);if(error)return alert('ما تحذفش المنتوج.');await loadProducts();await renderDashboard()}
$('#cartButton').onclick=openCart;$('#overlay').onclick=closeCart;document.querySelectorAll('[data-close="cartPanel"]').forEach(b=>b.onclick=closeCart);document.querySelectorAll('[data-close="checkoutModal"]').forEach(b=>b.onclick=()=>$('#checkoutModal').close());document.querySelectorAll('[data-close="productModal"]').forEach(b=>b.onclick=()=>$('#productModal').close());$('#checkoutButton').onclick=()=>$('#checkoutModal').showModal();$('#checkoutForm').onsubmit=createOrder;$('#newProduct').onclick=()=>openProduct();$('#leaveDashboard').onclick=()=>location.hash='#home';$('#productForm').onsubmit=saveProduct;$('#addDemoOrder').hidden=true;window.addEventListener('hashchange',()=>location.hash==='#dashboard'?enterDashboard():location.reload());$('#year').textContent=new Date().getFullYear();if(location.hash==='#dashboard')enterDashboard();loadProducts();
